### ISSUE TITLE
Debian package for vim-easymotion

### ISSUE THREAD

**Issue by jpleau** [haya14busa/haya14busa#13]
Hello, I plan to package vim-easymotion into the Debian archive. I'm just letting you know in advance :)

If you have any questions / comments, feel free to contact me: jason@jpleau.ca 

Thank you for this great plugin !

**Comment by jpleau** [comment]
I forgot something in my previous post:

Are all files licensed under "Creative Commons Attribution-ShareAlike 3.0 Unported" ? There's no copyright mention anywhere except in the documentation, just want to make sure !

**Comment by jpleau** [comment]
Sorry for the noise again. I found some copyrights (MIT) under the autoload/EasyMotion plugin. I noticed that were is a "vital" and "Over" library, those I'm really not sure how to give appropriate copyrights (ie: I can't tell if you modified them or not, some files are different than their original sources. Adding copyright headers on everyfile  would clear this up!)

**Comment by haya14busa** [comment]
The original file which @Lokaltog wrote are under "Creative Commons Attribution-ShareAlike 3.0 Unported"
1. `plugin/EasyMotion.vim`
2. `autoload/EasyMotion.vim`

and the new files which I added to improve it are under "MIT" licence
1. `autoload/EasyMotion/` directory

#### Licence of Library

vital.vim: https://github.com/vim-jp/vital.vim#license
vital-over: https://github.com/osyo-manga/vital-over#license

Both licence are [NYSL](http://www.kmonos.net/nysl/index.en.html).
1. `autoload/vital.vim`
2. `autoload/vital/` directory

> Adding copyright headers on everyfile would clear this up!)

I cannot add copyright headers for library files, but is my explanation ok?

**Comment by Lokaltog** [comment]
Since the CC-SA license is better suited for other types of creative works, I've relicensed most of my other source code to MIT. It's fine by me if you want to relicense the entire EasyMotion code base to MIT too to make it a bit simpler.

**Comment by haya14busa** [comment]
Thanks for the reply, @Lokaltog!

> It's fine by me if you want to relicense the entire EasyMotion code base to MIT too to make it a bit simpler.

Since, you agreed with changeing licence to MIT, I'll relicense it to MIT.

**Comment by haya14busa** [comment]
I changed license of easymotion to MIT.

**Comment by jpleau** [comment]
Big thanks a lot to both of you ! 

This clears up all my interrogations :)
